dist: trusty
sudo: false

jobs:
  include:
    - stage: VM
      dist: trusty
      sudo: required
      services:
        - docker


before_script:
  - export PATH=$HOME/.beamup/cli/:$PATH

script:
  - ./run.sh
