dist: trusty
sudo: false
env:
  - BEAMUP_BENCHMARK=TRAVIS_CONTAINER

jobs:
  include:
    - stage: Container
      dist: trusty
      sudo: false
      env: BEAMUP_BENCHMARK=TRAVIS_CONTAINER

    - stage: VM
      dist: trusty
      sudo: required
      env: BEAMUP_BENCHMARK=TRAVIS_VM
      services:
        - docker


before_script:
  - export PATH=$HOME/.beamup/cli/:$PATH

script:
  - ./run.sh
