language: erlang
otp_release:
  - 20.1.2

jobs:
  include:
    - stage: Container
      dist: trusty
      sudo: false
      env: BENCHMARK_SUBJECT=TravisContainer

    - stage: VM
      dist: trusty
      sudo: required
      env: BENCHMARK_SUBJECT=TravisVM
      services:
        - docker
      script:
        # Cache image to be comparable with builds
        # running in container
        - docker pull amd64/erlang:20.1.2
        - docker run --rm --init -ti amd64/erlang:20.1.2 echo "hello from the erlang container"
        - beamup echo "hello from the beamup container"
        - ./run.sh

install:
  - "true"

before_script:
  - export PATH=$HOME/.beamup/cli/:$PATH

script:
  - ./run.sh
